version: 2.1
orbs:
  python: circleci/python@1.2
workflows:
  ci:
    jobs:
      - build-and-test
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements_dev.txt
      - run:
          name: Run tests
          command: coverage run -m unittest discover
      - run:
          name: Upload coverage result
          command: bash <(curl -s https://codecov.io/bash)
