version: 2.1
orbs:
  python: circleci/python@1.4
workflows:
  ci:
    jobs:
      - build-and-test
      - static-analysis
jobs:
  static-analysis:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          cache-version: dev
          pip-dependency-file: requirements_dev.txt
      - run:
          name: Run static-analysis
          command: pre-commit run --all-files
  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          cache-version: prod
          pip-dependency-file: requirements.txt
      - python/install-packages:
          pkg-manager: pip
          cache-version: dev
          pip-dependency-file: requirements_dev.txt
      - run:
          name: Run tests
          command: coverage run -m unittest discover
      - run:
          name: Upload coverage result
          command: bash <(curl -s https://codecov.io/bash)
